vich_uploader:
  db_driver: orm

  metadata:
    auto_detection: true
    type: attribute

  mappings:
    tenant_images:
      uri_prefix: '/uploads'
      upload_destination: '%kernel.project_dir%/public/uploads'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
